### ISSUE TITLE
I meet this error,how can I do? I can‘t download the model. 

### ISSUE THREAD

**Issue by Y-pandaman** [JooyoungLeeETRI/CA_Entropy_Model#9]
Traceback (most recent call last):
  File "encode.py", line 48, in <module>
    encode(**vars(args))
  File "encode.py", line 19, in encode
    trainer = Tester_basemodel(model_dir)
  File "/home/yao/CA_Entropy_Model/CA_EntropyModel_Test/tester_basemodel.py", line 16, in __init__
    self.build_model()
  File "/home/yao/CA_Entropy_Model/CA_EntropyModel_Test/tester_basemodel.py", line 29, in build_model
    graph = self.load_graph(frozen_graph_filename)
  File "/home/yao/CA_Entropy_Model/CA_EntropyModel_Test/tester_basemodel.py", line 21, in load_graph
    graph_def.ParseFromString(f.read())
  File "/home/yao/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 11
8, in read
    self._preread_check()
  File "/home/yao/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 78
, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/yao/anaconda3/envs/tensorflow/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/yao/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py",
line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: ./models/MSEopt/Base_model/5/saved_model.pb

**Comment by JooyoungLeeETRI** [comment]
The model files are still available. If you have any problem, please try to download them via https://drive.google.com/open?id=1NqIYWOJP4o_JbUl2n2SdxezZNVdpBw5c

I'll close this issue. If you have any problem, please let me know through the next thread you've opened.
